### ISSUE TITLE
Config error output swallowed in jest

### ISSUE THREAD

**Issue by jpoehnelt** [wikimedia/eslint-docgen#125]
When using jest to run the tests I do not get any useful output from `assertValidConfig`:

```sh
process.exit called with "1"
  at assertValidConfig (node_modules/eslint-docgen/src/write-docs-from-tests.js:30:11)
  at Object.<anonymous> (node_modules/eslint-docgen/src/write-docs-from-tests.js:34:1)
  at Object.<anonymous> (node_modules/eslint-docgen/src/rule-tester.js:15:32)
 ```

**Comment by jpoehnelt** [comment]
Patching in `throw new Error(configErrors.map( ( error ) => formatter.error( error ) ).join( '\n' ) );` worked for me. I'll look a little further and see about submitting a PR.

**Comment by edg2s** [comment]
Thanks! Sorry I missed this over the Christmas break...
